### ISSUE TITLE
Build Issue on Ubunto

### ISSUE THREAD

**Issue by K4wkz** [Heep042/m0dular-csgo#18]
I already installed everything necessary but i still getting this error

`
ninja: Entering directory build'

[1/63] Precompiling header ../pch/cpp_pch.h.
FAILED: m0dular@sha/cpp_pch.h.gch 
c++ -Im0dular@sha -I. -I.. -I../pch -I../gui/menu/imgui -I/usr/include/SDL2 -I/usr/include/libdrm -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DAIMBOT_THREADING -D_HAS_STATIC_RTTI=0 -DTESTING_FEATURES -DPT_VISUALS -fPIC -D_REENTRANT -pthread -include global_defines.h -fno-rtti -Wno-non-virtual-dtor -Wno-strict-aliasing -fvisibility=hidden -flto=thin -gsplit-dwarf -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-math-errno -fno-ident -DM0DULAR_CHEAT -x c++-header -MD -MQ 'm0dular@sha/cpp_pch.h.gch' -MF 'm0dular@sha/cpp_pch.h.gch.d' -o 'm0dular@sha/cpp_pch.h.gch' -c ../pch/cpp_pch.h
cc1plus: error: unrecognized argument to ‘-flto=’ option: ‘thin’
cc1plus: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling

[2/63] Precompiling header ../pch/cpp_pch.h.

FAILED: clm0dular@exe/cpp_pch.h.gch 
c++ -Iclm0dular@exe -I. -I.. -I../pch -I../gui/menu/imgui -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DAIMBOT_THREADING -D_HAS_STATIC_RTTI=0 -DTESTING_FEATURES -DPT_VISUALS -pthread -include global_defines.h -fno-rtti -Wno-non-virtual-dtor -Wno-strict-aliasing -fvisibility=hidden -flto=thin -gsplit-dwarf -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-math-errno -fno-ident -DM0DULAR_CLIENT -x c++-header -MD -MQ 'clm0dular@exe/cpp_pch.h.gch' -MF 'clm0dular@exe/cpp_pch.h.gch.d' -o 'clm0dular@exe/cpp_pch.h.gch' -c ../pch/cpp_pch.h
cc1plus: error: unrecognized argument to ‘-flto=’ option: ‘thin’
cc1plus: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling

[3/63] Precompiling header ../pch/cpp_pch.h.

FAILED: mlm0dular@sha/cpp_pch.h.gch 
c++ -Imlm0dular@sha -I. -I.. -I../pch -I../gui/menu/imgui -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DAIMBOT_THREADING -D_HAS_STATIC_RTTI=0 -DTESTING_FEATURES -DPT_VISUALS -fPIC -pthread -include global_defines.h -fno-rtti -Wno-non-virtual-dtor -Wno-strict-aliasing -fvisibility=hidden -flto=thin -gsplit-dwarf -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-math-errno -fno-ident -DM0DULAR_CLIENT -x c++-header -MD -MQ 'mlm0dular@sha/cpp_pch.h.gch' -MF 'mlm0dular@sha/cpp_pch.h.gch.d' -o 'mlm0dular@sha/cpp_pch.h.gch' -c ../pch/cpp_pch.h
cc1plus: error: unrecognized argument to ‘-flto=’ option: ‘thin’
cc1plus: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling

[4/63] Precompiling header ../pch/cpp_pch.h.

FAILED: keybind_test@exe/cpp_pch.h.gch 
c++ -Ikeybind_test@exe -I. -I.. -I../pch -I../gui/menu/imgui -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DAIMBOT_THREADING -D_HAS_STATIC_RTTI=0 -DTESTING_FEATURES -DPT_VISUALS -pthread -include global_defines.h -fno-rtti -Wno-non-virtual-dtor -Wno-strict-aliasing -fvisibility=hidden -flto=thin -gsplit-dwarf -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-math-errno -fno-ident -x c++-header -MD -MQ 'keybind_test@exe/cpp_pch.h.gch' -MF 'keybind_test@exe/cpp_pch.h.gch.d' -o 'keybind_test@exe/cpp_pch.h.gch' -c ../pch/cpp_pch.h
cc1plus: error: unrecognized argument to ‘-flto=’ option: ‘thin’
cc1plus: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling

[5/63] Compiling C object 'keycode_clib@sta/modules_keycode_keyid.c.o'.

FAILED: keycode_clib@sta/modules_keycode_keyid.c.o 
cc -Ikeycode_clib@sta -I. -I.. -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O3 -DAIMBOT_THREADING -D_HAS_STATIC_RTTI=0 -DTESTING_FEATURES -DPT_VISUALS -fPIC -include global_defines.h -fno-rtti -Wno-non-virtual-dtor -Wno-strict-aliasing -fvisibility=hidden -flto=thin -gsplit-dwarf -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-math-errno -fno-ident -MD -MQ 'keycode_clib@sta/modules_keycode_keyid.c.o' -MF 'keycode_clib@sta/modules_keycode_keyid.c.o.d' -o 'keycode_clib@sta/modules_keycode_keyid.c.o' -c ../modules/keycode/keyid.c
cc1: warning: command line option ‘-Wno-non-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/D/ObjC++ but not for C
cc1: error: unrecognized argument to ‘-flto=’ option: ‘thin’
cc1: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling

[6/63] Compiling C++ object 'module_id@sta/bits_identify.cpp.o'.

FAILED: module_id@sta/bits_identify.cpp.o 
c++ -Imodule_id@sta -I. -I.. -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DAIMBOT_THREADING -D_HAS_STATIC_RTTI=0 -DTESTING_FEATURES -DPT_VISUALS -fPIC -include global_defines.h -fno-rtti -Wno-non-virtual-dtor -Wno-strict-aliasing -fvisibility=hidden -flto=thin -gsplit-dwarf -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-math-errno -fno-ident '-DMODULE_IDENTIFICATION="x52"' -MD -MQ 'module_id@sta/bits_identify.cpp.o' -MF 'module_id@sta/bits_identify.cpp.o.d' -o 'module_id@sta/bits_identify.cpp.o' -c ../bits/identify.cpp
cc1plus: error: unrecognized argument to ‘-flto=’ option: ‘thin’
cc1plus: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling
ninja: build stopped: subcommand failed.
`

**Comment by Heep042** [comment]
Please use a up to date clang for compiling (pass CC=clang CXX=clang++ as variables just before the meson command), or remove -flto flag from meson.build
